In [3]:
import torch

In [12]:
import numpy as np
xy = np.loadtxt("./data/diabetes.csv.gz", delimiter=',', dtype=np.float32)
x_data = torch.from_numpy(xy[:, :-1])
y_data = torch.from_numpy(xy[:, [-1]]) # 加上方括号才表示矩阵，直接写[:, -1]拿出来的是一维向量
x_data, y_data

(tensor([[-0.2941,  0.4874,  0.1803,  ...,  0.0015, -0.5312, -0.0333],
         [-0.8824, -0.1457,  0.0820,  ..., -0.2072, -0.7669, -0.6667],
         [-0.0588,  0.8392,  0.0492,  ..., -0.3055, -0.4927, -0.6333],
         ...,
         [-0.4118,  0.2161,  0.1803,  ..., -0.2191, -0.8574, -0.7000],
         [-0.8824,  0.2663, -0.0164,  ..., -0.1028, -0.7686, -0.1333],
         [-0.8824, -0.0653,  0.1475,  ..., -0.0939, -0.7976, -0.9333]]),
 tensor([[0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [0.],
         [0.],
         [0.],
         [1.],
         [0.],
         [1.],
         [1.],
         [0.],
         [0.],
         [0.],
         [0.],
         [1.],
         [1.],
         [1.],
         [1.],
         [0.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [0.],
         [0.],
   

![模型结构](./data/model_structure.png)

神经网络的本质：  
寻找一种非线性空间变换函数  


step 1: 准备数据集  
step 2：构建网络模型  
step 3：构造损失函数和优化器  
step 4：训练周期  

In [29]:
class Model(torch.nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.linear1 = torch.nn.Linear(8, 6)
    self.linear2 = torch.nn.Linear(6, 4)
    self.linear3 = torch.nn.Linear(4, 2)
    self.linear4 = torch.nn.Linear(2, 1)
    self.sigmoid = torch.nn.Sigmoid()
  
  def forward(self, x):
    x = self.sigmoid(self.linear1(x))
    x = self.sigmoid(self.linear2(x))
    x = self.sigmoid(self.linear3(x))
    x = self.sigmoid(self.linear4(x))
    return x

model = Model()

In [15]:
criterion = torch.nn.BCELoss(reduction='mean')
optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

In [30]:
for epoch in range(1000000):
  # Forward
  y_pred = model(x_data)
  loss = criterion(y_pred, y_data)
  print(epoch, loss.item())

  # Backward
  optimizer.zero_grad()
  loss.backward()

  # Update
  optimizer.step()


        

0 0.6843605041503906
1 0.6843605041503906
2 0.6843605041503906
3 0.6843605041503906
4 0.6843605041503906
5 0.6843605041503906
6 0.6843605041503906
7 0.6843605041503906
8 0.6843605041503906
9 0.6843605041503906
10 0.6843605041503906
11 0.6843605041503906
12 0.6843605041503906
13 0.6843605041503906
14 0.6843605041503906
15 0.6843605041503906
16 0.6843605041503906
17 0.6843605041503906
18 0.6843605041503906
19 0.6843605041503906
20 0.6843605041503906
21 0.6843605041503906
22 0.6843605041503906
23 0.6843605041503906
24 0.6843605041503906
25 0.6843605041503906
26 0.6843605041503906
27 0.6843605041503906
28 0.6843605041503906
29 0.6843605041503906
30 0.6843605041503906
31 0.6843605041503906
32 0.6843605041503906
33 0.6843605041503906
34 0.6843605041503906
35 0.6843605041503906
36 0.6843605041503906
37 0.6843605041503906
38 0.6843605041503906
39 0.6843605041503906
40 0.6843605041503906
41 0.6843605041503906
42 0.6843605041503906
43 0.6843605041503906
44 0.6843605041503906
45 0.684360504150390

In [21]:
if epoch % 100000 == 99999:
    y_pred_label = torch.where(y_pred>=0.5, torch.tensor([1.0]), torch.tensor([0.0]))
    #print(y_pred_label, y_data)
    acc = torch.eq(y_pred_label, y_data).sum().item()/y_data.size(0)
    print("loss = ",loss.item(), "acc = ",acc)
    

loss =  0.412270724773407 acc =  0.7905138339920948


In [22]:
from sklearn.metrics import confusion_matrix, classification_report

In [25]:
confusion_matrix(y_pred_label, y_data),

(array([[177,  73],
        [ 86, 423]], dtype=int64),)

In [26]:
classification_report(y_pred_label, y_data)

'              precision    recall  f1-score   support\n\n         0.0       0.67      0.71      0.69       250\n         1.0       0.85      0.83      0.84       509\n\n    accuracy                           0.79       759\n   macro avg       0.76      0.77      0.77       759\nweighted avg       0.79      0.79      0.79       759\n'